api_platform:
  formats:
    json: ['application/merge-patch+json']
    jsonld: ['application/ld+json']
    form: ['multipart/form-data']
  patch_formats:
    json: ['application/merge-patch+json']
    form: ['multipart/form-data']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  title: 'Bluette API'
  version: '1.0.0'
  description: Des petites histoires, sans prétention !
  show_webby: false
  defaults:
    pagination_items_per_page: 20 # Default value