nelmio_cors:
    defaults:
        # origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin', 'x-csrf-token','X-Custom-Auth']
        # expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api': 
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Custom-Auth']
            max_age: 3600
        '^/': 
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization', 'X-Custom-Auth']
            max_age: 3600