vich_uploader:
    db_driver: orm # or mongodb or phpcr

    metadata:
        type: attribute

    mappings:
        image:
            uri_prefix: /api/images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true